require:
  - database_validations/rubocop/cops
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - standard
  - standard-custom
  - standard-performance

AllCops:
  NewCops: enable
